name: Release candidate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Release candidate"