name: Build & upload to Google Play

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/devlin.keystore'
          encodedString: ${{ secrets.PROD_SIGNING_KEY_BASE64 }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Build AAB
        run: ./gradlew bundlePro
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.PROD_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.PROD_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.PROD_KEY_STORE_PASSWORD }}
      - name: Sign Release build
        run: jarsigner -keystore keystore/devlin.keystore -storepass "${{ secrets.PROD_KEY_STORE_PASSWORD }}" app/build/outputs/bundle/ProRelease/app-Pro-release.aab eric
      - name: Downcase target
        id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.event.inputs.target }}
      - name: Create service_account.json
        run: echo '${{ secrets.GOOGLE_V1 }}' > service_account.json

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1.0.17
        with:
          serviceAccountJson: service_account.json
          packageName: com.simplicity.simplicityaclientforreddit
          releaseFiles: app/build/outputs/bundle/ProRelease/app-Pro-release.aab
          status: draft
          track: internal
