name: Test

on:
  workflow_dispatch:
    inputs:
      failJob:
        description: Fail the job?
        type: boolean
        required: true
        default: false

jobs:
  writing:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.min_version.outputs.min_version  }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradle executable
        run: chmod +x ./gradlew
      - name: Write env variable
        id: metadata
        run: |
          echo "test_value=Wohoo" >> $GITHUB_OUTPUT
      - name: Gradle task test
        id: min_version
        run: echo "min_version=$(${{github.workspace}}/gradlew -q getMinVersion)" >> $GITHUB_OUTPUT

  showing:
    runs-on: ubuntu-latest
    needs: writing
    steps:
      - name: Posting saved env value
        id: metadata
        run: |
          echo "${{ needs.writing.outputs.output1 || 'Could not find output'}}"