name: Test

on:
  workflow_dispatch:
    inputs:
      failJob:
        description: Fail the job?
        type: boolean
        required: true
        default: false

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.test.outputs.test  }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          ref: ${{ GITHUB_REF#refs/heads/ }}
          distribution: temurin
          java-version: 11
  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.test.outputs.test  }}
    steps:
      - name: Try to fail
        run: exit 1

  showing:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ job1, job2 ]
    steps:
      - name: Sending mattermost for job1
        if: (needs.job1.result == 'success')
        run: |
          echo "${{ needs.job1.outputs.output1 || 'Could not find output'}}"
      - name: Sending mattermost for job2
        if: (needs.job2.result == 'success')
        run: |
          echo "${{ needs.job2.outputs.output1 || 'Could not find output'}}"