name: Test

on:
  workflow_dispatch:
    inputs:
      failJob:
        description: Fail the job?
        type: boolean
        required: true
        default: false
jobs:
  synchronize_with_lokalise:
    runs-on: ubuntu-latest
    - name: Check if there is any change
      id: get_changes
      run: echo "changed=5" >> $GITHUB_ENV
    - name: Echo changes
      if: env.changed != 0
      id: echo_changes
      run: echo "It has changed!"
