name: Test

on:
  workflow_dispatch:
    inputs:
      failJob:
        description: Fail the job?
        type: boolean
        required: true
        default: false
jobs:
  synchronize_with_lokalise:
    runs-on: ubuntu-latest
      - name: Check if there is any change
        id: get_changes
        run: echo "changed=5"

    outputs:
      has_changes: steps.get_changes.outputs.changed != 0

  create_and_open_pull_request:
    runs-on: ubuntu-latest
    needs: [ synchronize_with_lokalise ]
    steps:

      - name: Print changed name
        run: echo ${{ needs.synchronize_with_lokalise.outputs.has_changes }}